### ISSUE TITLE
Mozilla 今天公布了新的 API 计划

### ISSUE THREAD

**Issue by zhuzhuor** [whuhacker/Unblock-Youku-Firefox#14]
官方文章见 https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/
说是要弄类似 Chrome 这样的 API 系统，要 deprecate  旧的 XPCOM 和 XUL based addons
这个会对这扩展程序有影响吗，是好事还是坏事

**Comment by whuhacker** [comment]
挺好的，之后就可以和 Chrome 共用一个代码库了。未来 12 到 18 个月会做出改变吧。

**Comment by zhuzhuor** [comment]
@whuhacker 我看到没有 proxy API，不过12个月还早，可能在那之前会加上吧

**Comment by whuhacker** [comment]
@zhuzhuor 到时候估计 Firefox 整个项目会重写，不过考虑和 Chrome 的 API 兼容，工作量应该不大。
