### ISSUE TITLE
在旧版本firefox上面  statuebaricon丢失

### ISSUE THREAD

**Issue by FateRover** [whuhacker/Unblock-Youku-Firefox#18]
老版本firefox 例如 35上面图标丢失。
具体表现为安装完扩展，在附加组件页面有该项，但是在附加组件栏没有按钮

**Comment by yan12125** [comment]
似乎是和#17相同的問題？

現在Firefox 57已經出了，這個套件也不能用了(#14)，我想這個issue可以關了。

**Comment by whuhacker** [comment]
即將適配 WebExtension
